(() => {
'use strict';
const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);const ui={wave:$('wave'),score:$('score'),best:$('best'),combo:$('combo'),hp:$('hp-bar'),shield:$('shield-bar'),boss:$('boss-bar'),bossHp:$('boss-hp'),bossName:$('boss-name'),bossText:$('boss-hp-text'),toast:$('toast'),overlay:$('overlay'),menu:$('menu-panel'),over:$('gameover-panel'),upgrade:$('upgrade-panel'),upgrades:$('upgrade-list'),finalScore:$('final-score'),finalWave:$('final-wave'),ship:$('ship-name'),sound:$('sound-state'),dash:$('dash-hint')};
const W=480,H=800,TAU=Math.PI*2;let state='menu',last=0,score=0,wave=1,combo=1,comboTimer=0,best=Number(localStorage.getItem('neon-strike-best')||0),soundOn=localStorage.getItem('neon-strike-sound')!=='off',shake=0,spawnTimer=.4,waveKills=0,nextWaveKills=8,dashCooldown=0,boss=null;
const input={x:W/2,y:H-100,active:false,startX:0,startY:0};const player={x:W/2,y:H-100,r:18,speed:330,hp:100,shield:70,maxShield:70,fire:0,damage:1,fireRate:.16,bulletSpeed:650,shots:1,spread:.13,invuln:0};const bullets=[],enemies=[],particles=[],stars=[];for(let i=0;i<90;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:Math.random()*2+.5,v:15+Math.random()*35});
const ships=[{name:'INTERCEPTOR',speed:1,damage:1},{name:'BLASTER',speed:.9,damage:1.35},{name:'PHANTOM',speed:1.2,damage:.85}];let shipIndex=0;const upgrades=[['OVERDRIVE','Fire rate +18%',()=>player.fireRate*=.82],['PLASMA CORE','Damage +25%',()=>player.damage*=1.25],['NANO ARMOR','Repair 30 HP',()=>player.hp=Math.min(100,player.hp+30)],['VOID SHIELD','Shield +30',()=>{player.maxShield+=30;player.shield=player.maxShield}],['MULTI SHOT','Add one projectile',()=>player.shots=Math.min(3,player.shots+1)],['THRUSTERS','Movement speed +15%',()=>player.speed*=1.15]];
function beep(freq,dur=.06,type='sine',vol=.025){if(!soundOn)return;try{const a=beep.ctx||(beep.ctx=new(window.AudioContext||window.webkitAudioContext)());if(a.state==='suspended')a.resume();const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.stop(a.currentTime+dur+.02)}catch(e){}}
function reset(){score=0;wave=1;combo=1;comboTimer=0;waveKills=0;nextWaveKills=8;spawnTimer=.4;boss=null;bullets.length=enemies.length=particles.length=0;Object.assign(player,{x:W/2,y:H-100,hp:100,shield:player.maxShield,fire:0,damage:ships[shipIndex].damage,fireRate:.16,shots:1,invuln:0,speed:330*ships[shipIndex].speed});ui.boss.classList.add('hidden');updateHud()}
function updateHud(){ui.wave.textContent=wave;ui.score.textContent=Math.floor(score);ui.best.textContent=Math.max(best,Math.floor(score));ui.combo.textContent='x'+combo;ui.hp.style.width=Math.max(0,player.hp)+'%';ui.shield.style.width=Math.max(0,player.shield/player.maxShield*100)+'%';ui.dash.textContent=dashCooldown<=0?'DASH READY':'DASH '+dashCooldown.toFixed(1)+'s'}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),900)}function particle(x,y,color,amount=8,power=130){for(let i=0;i<amount;i++){const a=Math.random()*TAU,s=Math.random()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.4,max:.65,r:1+Math.random()*3,color})}}
function spawn(type){const x=30+Math.random()*(W-60);if(type==='boss'){boss={x:W/2,y:85,r:48,hp:260+wave*60,max:260+wave*60,t:0};ui.boss.classList.remove('hidden');toast('⚠ BOSS INBOUND');beep(110,.3,'sawtooth',.05);return}const types=['drone','swarm','tank','shooter','chaser'];type=type||types[Math.floor(Math.random()*Math.min(types.length,2+Math.floor(wave/3)))];const d={drone:[14,55,1,10],swarm:[9,100,1,18],tank:[25,35,3,35],shooter:[16,42,2,25],chaser:[13,70,2,30]}[type];enemies.push({type,x,y:-30,r:d[0],speed:d[1]+wave*2,hp:d[2]+Math.floor(wave/5),value:d[3],shoot:1+Math.random()*2,t:Math.random()*3})}
function shoot(){for(let i=0;i<player.shots;i++){const off=(i-(player.shots-1)/2)*player.spread;bullets.push({x:player.x,y:player.y-22,vx:Math.sin(off)*player.bulletSpeed,vy:-Math.cos(off)*player.bulletSpeed,r:4,damage:player.damage})}beep(720,.035,'square',.012)}
function damagePlayer(amount){if(player.invuln>0)return;if(player.shield>0){const a=Math.min(player.shield,amount);player.shield-=a;amount-=a}player.hp-=amount;player.invuln=.55;shake=7;particle(player.x,player.y,'#ff5d87',14,180);beep(100,.15,'sawtooth',.04);if(player.hp<=0)gameOver()}
function killEnemy(i){const e=enemies[i];score+=e.value*combo;waveKills++;combo=Math.min(12,combo+1);comboTimer=2.5;particle(e.x,e.y,e.type==='tank'?'#ff5d87':'#7ef4d0',e.type==='tank'?22:10,220);beep(360,.05,'triangle',.025);enemies.splice(i,1);if(waveKills>=nextWaveKills&&!boss)startUpgrade()}
function update(dt){for(const s of stars){s.y+=s.v*dt;if(s.y>H)s.y=0}if(comboTimer>0){comboTimer-=dt;if(comboTimer<=0)combo=1}dashCooldown=Math.max(0,dashCooldown-dt);player.invuln=Math.max(0,player.invuln-dt);if(input.active&&state==='playing'){const dx=input.x-player.x,dy=input.y-player.y,d=Math.hypot(dx,dy);if(d>4){player.x+=dx/d*player.speed*dt;player.y+=dy/d*player.speed*dt}player.fire-=dt;if(player.fire<=0){shoot();player.fire=player.fireRate}}player.x=Math.max(player.r,Math.min(W-player.r,player.x));player.y=Math.max(100,Math.min(H-player.r-20,player.y));spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnTimer=Math.max(.28,1.05-wave*.045)*(.75+Math.random()*.45)}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<-30||b.x<-30||b.x>W+30)bullets.splice(i,1)}
for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];e.t+=dt;if(e.type==='chaser'){const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*e.speed*dt*.55;e.y+=e.speed*dt*.45}else e.y+=e.speed*dt;if(e.type==='shooter'&&e.y>80){e.shoot-=dt;if(e.shoot<=0){e.shoot=2;const a=Math.atan2(player.y-e.y,player.x-e.x);bullets.push({enemy:true,x:e.x,y:e.y,vx:Math.cos(a)*190,vy:Math.sin(a)*190,r:5,damage:12})}}if(e.y>H+35){enemies.splice(i,1);damagePlayer(8);continue}if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+player.r){enemies.splice(i,1);damagePlayer(e.type==='tank'?28:18);continue}for(let j=bullets.length-1;j>=0;j--){const b=bullets[j];if(b.enemy)continue;if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){e.hp-=b.damage;bullets.splice(j,1);particle(b.x,b.y,'#fff',3,70);if(e.hp<=0)killEnemy(i);break}}}
if(boss){boss.t+=dt;boss.x=W/2+Math.sin(boss.t*.8)*150;boss.y=85+Math.sin(boss.t*1.7)*22;const phase=boss.hp<boss.max*.5?1:0;if(Math.random()<dt*(.9+phase*.6)){const a=Math.atan2(player.y-boss.y,player.x-boss.x);bullets.push({enemy:true,x:boss.x,y:boss.y,vx:Math.cos(a)*210,vy:Math.sin(a)*210,r:6,damage:15})}for(let j=bullets.length-1;j>=0;j--){const b=bullets[j];if(!b.enemy&&Math.hypot(b.x-boss.x,b.y-boss.y)<boss.r+b.r){boss.hp-=b.damage;bullets.splice(j,1);particle(b.x,b.y,'#ff5d87',4,90)}}if(Math.hypot(boss.x-player.x,boss.y-player.y)<boss.r+player.r)damagePlayer(25);if(boss.hp<=0){score+=1500+wave*300;particle(boss.x,boss.y,'#ff5d87',70,360);toast('BOSS DESTROYED +BONUS');beep(70,.5,'sawtooth',.06);boss=null;ui.boss.classList.add('hidden');waveKills=nextWaveKills;setTimeout(startUpgrade,350)}else{ui.bossHp.style.width=Math.max(0,boss.hp/boss.max*100)+'%';ui.bossText.textContent=Math.ceil(boss.hp/boss.max*100)+'%';ui.bossName.textContent='OVERLORD // WAVE '+wave}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt;if(p.life<=0)particles.splice(i,1)}if(shake>0)shake*=.88;updateHud()}
function render(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#050a14';ctx.fillRect(0,0,W,H);for(const s of stars){ctx.fillStyle=`rgba(126,244,208,${.18+s.s/5})`;ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.strokeStyle='rgba(126,244,208,.035)';for(let y=120;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const b of bullets){ctx.fillStyle=b.enemy?'#ff5d87':'#fff';ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,TAU);ctx.fill();ctx.shadowBlur=0}for(const e of enemies){const glow=e.type==='tank'?'#ff5d87':e.type==='shooter'?'#9b8cff':'#7ef4d0';ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=16;ctx.shadowColor=glow;ctx.fillStyle=glow;ctx.beginPath();if(e.type==='tank')ctx.rect(-e.r,-e.r,e.r*2,e.r*2);else ctx.arc(0,0,e.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#06101b';ctx.beginPath();ctx.arc(0,0,e.r*.35,0,TAU);ctx.fill();ctx.restore()}if(boss){ctx.save();ctx.translate(boss.x,boss.y);ctx.rotate(boss.t*.5);ctx.strokeStyle='#ff5d87';ctx.lineWidth=6;ctx.shadowBlur=25;ctx.shadowColor='#ff5d87';ctx.beginPath();ctx.arc(0,0,boss.r,0,TAU);ctx.stroke();ctx.fillStyle='#ff5d87';ctx.beginPath();for(let i=0;i<8;i++){const a=i*TAU/8;ctx.lineTo(Math.cos(a)*boss.r,Math.sin(a)*boss.r)}ctx.fill();ctx.restore()}ctx.save();ctx.translate(player.x,player.y);ctx.globalAlpha=player.invuln>0&&Math.floor(player.invuln*14)%2?.35:1;ctx.shadowBlur=22;ctx.shadowColor='#7ef4d0';ctx.fillStyle='#7ef4d0';ctx.beginPath();ctx.moveTo(0,-24);ctx.lineTo(17,19);ctx.lineTo(0,13);ctx.lineTo(-17,19);ctx.closePath();ctx.fill();ctx.fillStyle='#06131a';ctx.beginPath();ctx.arc(0,2,6,0,TAU);ctx.fill();ctx.restore();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r,p.r)}ctx.globalAlpha=1;ctx.restore()}
function loop(ts){if(state==='playing'){const dt=Math.min(.033,(ts-last)/1000);last=ts;update(dt);render();requestAnimationFrame(loop)}else render()}function start(){reset();state='playing';ui.overlay.classList.add('hidden');ui.menu.classList.add('hidden');ui.over.classList.add('hidden');ui.upgrade.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function startUpgrade(){if(state!=='playing')return;state='upgrade';input.active=false;const pool=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);ui.upgrades.innerHTML='';pool.forEach(([name,desc,fn])=>{const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<strong>${name}</strong><small>${desc}</small>`;b.onclick=()=>{fn();wave++;waveKills=0;nextWaveKills=8+wave*2;state='playing';ui.upgrade.classList.add('hidden');ui.overlay.classList.add('hidden');toast('UPGRADE INSTALLED');if(wave%5===0)setTimeout(()=>{if(state==='playing')spawn('boss')},500);last=performance.now();requestAnimationFrame(loop)};ui.upgrades.appendChild(b)});ui.overlay.classList.remove('hidden');ui.menu.classList.add('hidden');ui.over.classList.add('hidden');ui.upgrade.classList.remove('hidden')}
function gameOver(){state='over';input.active=false;best=Math.max(best,Math.floor(score));localStorage.setItem('neon-strike-best',best);ui.finalScore.textContent=Math.floor(score);ui.finalWave.textContent=wave;ui.overlay.classList.remove('hidden');ui.over.classList.remove('hidden');ui.menu.classList.add('hidden');ui.upgrade.classList.add('hidden');beep(65,.4,'sawtooth',.05);render()}
function toPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;canvas.setPointerCapture(e.pointerId);const p=toPoint(e);Object.assign(input,{x:p.x,y:p.y,startX:p.x,startY:p.y,active:true})});canvas.addEventListener('pointermove',e=>{if(input.active){const p=toPoint(e);input.x=p.x;input.y=p.y}});canvas.addEventListener('pointerup',e=>{if(input.active){const p=toPoint(e),d=Math.hypot(p.x-input.startX,p.y-input.startY);if(d>100&&dashCooldown<=0){const a=Math.atan2(p.y-input.startY,p.x-input.startX);player.x=Math.max(20,Math.min(W-20,player.x+Math.cos(a)*100));player.y=Math.max(110,Math.min(H-30,player.y+Math.sin(a)*100));dashCooldown=4;particle(player.x,player.y,'#9b8cff',18,240);beep(220,.08,'triangle',.035)}input.active=false}});canvas.addEventListener('pointercancel',()=>input.active=false);
$('start-btn').onclick=start;$('retry-btn').onclick=start;$('menu-btn').onclick=()=>{state='menu';ui.overlay.classList.remove('hidden');ui.menu.classList.remove('hidden');ui.over.classList.add('hidden');ui.upgrade.classList.add('hidden');render()};$('sound-btn').onclick=()=>{soundOn=!soundOn;localStorage.setItem('neon-strike-sound',soundOn?'on':'off');ui.sound.textContent=soundOn?'ON':'OFF';beep(500)};$('loadout-btn').onclick=()=>{shipIndex=(shipIndex+1)%ships.length;ui.ship.textContent=ships[shipIndex].name;toast('SHIP: '+ships[shipIndex].name)};ui.sound.textContent=soundOn?'ON':'OFF';ui.ship.textContent=ships[shipIndex].name;ui.best.textContent=best;render();window.__game={start,reset};
})();